- tomcat6/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat85/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
Add the possibility to use an existing Hazelcast instance by specifying its name.
> Add the possibility to use an existing Hazelcast instance

- tomcat-core/src/test/java/com/hazelcast/session/AbstractSessionExpireTest.java
- tomcat6/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat6/src/test/java/com/hazelcast/session/Tomcat6Configurator.java
- tomcat6/src/test/java/com/hazelcast/session/Tomcat6SessionExpireTest.java
- tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat7/src/test/java/com/hazelcast/session/Tomcat7AsyncConfigurator.java
- tomcat7/src/test/java/com/hazelcast/session/Tomcat7Configurator.java
- tomcat7/src/test/java/com/hazelcast/session/Tomcat7SessionExpireTest.java
- tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat8/src/test/java/Tomcat8SessionExpireTest.java
- tomcat8/src/test/java/com/hazelcast/session/Tomcat8AsyncConfigurator.java
- tomcat8/src/test/java/com/hazelcast/session/Tomcat8Configurator.java
- tomcat8/src/test/java/com/hazelcast/session/Tomcat8SessionExpireTest.java
- tomcat85/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat85/src/test/java/com/hazelcast/session/Tomcat85AsyncConfigurator.java
- tomcat85/src/test/java/com/hazelcast/session/Tomcat85Configurator.java
- tomcat85/src/test/java/com/hazelcast/session/Tomcat85SessionExpireTest.java
Implement findSessions() and return all sessions in the cluster so that sessions not connected to a cluster node anymore can be expired. Solves issue #39 .
> Implement findSessions() and return all sessions in the cluster.

- tomcat-core/src/main/java/com/hazelcast/session/HazelcastSession.java
Fixes: https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/issues/51
• Catch and log exceptions during deserialization
See also: https://github.com/edwardsmatt/hazelcast-cnfe-parallel-deployment-example
> Fixes ClassNotFoundException causing Internal Server Errors when using Parallel deployments (#51)

- tomcat-core/src/main/java/com/hazelcast/session/HazelcastInstanceFactory.java
- tomcat-core/src/main/java/com/hazelcast/session/P2PLifecycleListener.java
- tomcat6/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat85/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
Fixes #55.
This fix moves the initialization of the Hazelcast member instance on P2P mode to the startup of `HazelcastSessionManager` in order to access the context classloader. Please note that there might be still an issue if the context classloader changes dynamically, since Hazelcast doesn't allow to update the classloader after the initialization of the instance.
> Fix for context classloader issue

- README.md
- checkstyle/ClassHeader.txt
- pom.xml
- tomcat-core/src/main/java/com/hazelcast/session/ClientServerLifecycleListener.java
- tomcat-core/src/main/java/com/hazelcast/session/HazelcastInstanceFactory.java
- tomcat-core/src/main/java/com/hazelcast/session/HazelcastSession.java
- tomcat-core/src/main/java/com/hazelcast/session/HazelcastSessionChangeValve.java
- tomcat-core/src/main/java/com/hazelcast/session/HazelcastSessionCommitValve.java
- tomcat-core/src/main/java/com/hazelcast/session/P2PLifecycleListener.java
- tomcat-core/src/main/java/com/hazelcast/session/SessionManager.java
- tomcat-core/src/main/java/com/hazelcast/session/package-info.java
- tomcat-core/src/test/resources/hazelcast-1.xml
- tomcat-core/src/test/resources/hazelcast-2.xml
- tomcat-core/src/test/resources/hazelcast.xml
- tomcat6/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat6/src/main/java/com/hazelcast/session/package-info.java
- tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat7/src/main/java/com/hazelcast/session/package-info.java
- tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat8/src/main/java/com/hazelcast/session/package-info.java
- tomcat85/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat85/src/main/java/com/hazelcast/session/package-info.java
The classheaders are updated to 2019. Also, readme is updated for classloader and instance name issues.
> Changed copyright to 2019 and updated readme

- tomcat-core/src/main/java/com/hazelcast/session/LocalSessionsInvalidateListener.java
- tomcat6/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat85/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
Fixes #42 & #34 
Hazelcast calls in `HazelcastSessionManager.findSession(id)` method (`remove` and `set`) should be concurrent in order to provide thread-safe access to the session object. 
The depreciated usage of `EntryListener` is also replaced with `MapListener`.
> Updated the `findSession` method to fix concurrency issues

- pom.xml
After Hazelcast 3.9, the shutdown mechanism affected from the improvements on mastership claim process. With the usage of context classloader, the shutdown durations take longer time on tests. A 10 secs of `hazelcast.graceful.shutdown.max.wait` added to the master profile to make the tests complete in time.
> Updated master profile for shorter Hazelcast shutdown

- tomcat-core/src/test/java/com/hazelcast/session/nonsticky/AbstractNonStickySessionsTest.java
- tomcat-core/src/test/java/com/hazelcast/session/sticky/AbstractStickySessionsTest.java
The member instances are used to validate the session parameters that are kept in the cluster. They might not initialize, or join to the existing cluster because of the configuration. They are changed to client instances to overcome these issues.
> Changed the member instances to clients in two test cases

- pom.xml
Fixes compile and test errors occurring because of the merge of client and core modules in this https://github.com/hazelcast/hazelcast/pull/15366 for Hazelcast 4.0.
> Updated pom.xml dependencies for merging client & core modules

- pom.xml
- tomcat-core/src/main/java/com/hazelcast/session/ClientServerLifecycleListener.java
- tomcat-core/src/main/java/com/hazelcast/session/P2PLifecycleListener.java
fixes #53 
ClientConfig is created now in case of `before_start` event fired by Tomcat. This will enable operators to be able to configure hazelcast.xml/hazelcast-client.xml config path properly in `server.xml`
I was only able to reproduce the NPE in Spring Boot environment. That is why tests were passing with "start" event. We are changing it to `before_start` to guarantee custom hazelcast configuration.
> changed lifecycle events to before_start

- tomcat-core/src/main/java/com/hazelcast/session/HazelcastSession.java
- tomcat-core/src/main/java/com/hazelcast/session/SessionManager.java
- tomcat-core/src/test/java/com/hazelcast/session/nonsticky/AbstractNonStickySessionsTest.java
- tomcat6/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat6/src/test/java/com/hazelcast/session/nonsticky/Tomcat6ClientServerNonStickySessionsTest.java
- tomcat6/src/test/java/com/hazelcast/session/nonsticky/Tomcat6P2PNonStickySessionsTest.java
- tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat7/src/test/java/com/hazelcast/session/nonsticky/Tomcat7ClientServerNonStickySessionsTest.java
- tomcat7/src/test/java/com/hazelcast/session/nonsticky/Tomcat7P2PNonStickySessionsTest.java
- tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat8/src/test/java/com/hazelcast/session/nonsticky/Tomcat8ClientServerNonStickySessionsTest.java
- tomcat8/src/test/java/com/hazelcast/session/nonsticky/Tomcat8P2PNonStickySessionsTest.java
- tomcat85/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat85/src/test/java/com/hazelcast/session/nonsticky/Tomcat85ClientServerNonStickySessionsTest.java
- tomcat85/src/test/java/com/hazelcast/session/nonsticky/Tomcat85P2PNonStickySessionsTest.java
* If non-sticky sessions are configured, then refresh current object timestamps from the distributed session map.
* Adds tests to verify timestamps for non-sticky sessions.
> Fixes Inconsistent Session Timestamps when using non-sticky sessions (#48)

- README.md
- pom.xml
- tomcat-core/pom.xml
- tomcat-core/src/main/java/com/hazelcast/session/HazelcastSession.java
- tomcat-core/src/test/java/com/hazelcast/session/CustomAttribute.java
- tomcat-core/src/test/java/com/hazelcast/session/HazelcastGlobalKryoSerializer.java
- tomcat-core/src/test/java/com/hazelcast/session/TestServlet.java
- tomcat-core/src/test/java/com/hazelcast/session/nonsticky/AbstractNonStickySessionsTest.java
- tomcat-core/src/test/resources/hazelcast-client-default.xml
- tomcat8/pom.xml
- tomcat85/pom.xml
> Added support for all serialization methods in Hazelcast

- pom.xml
- tomcat9/pom.xml
- tomcat9/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat9/src/main/java/com/hazelcast/session/package-info.java
- tomcat9/src/test/java/com/hazelcast/session/AsyncServlet.java
- tomcat9/src/test/java/com/hazelcast/session/AsyncServletTest.java
- tomcat9/src/test/java/com/hazelcast/session/Java6ExcludeRule.java
- tomcat9/src/test/java/com/hazelcast/session/Tomcat9AsyncConfigurator.java
- tomcat9/src/test/java/com/hazelcast/session/Tomcat9Configurator.java
- tomcat9/src/test/java/com/hazelcast/session/Tomcat9MapNameTest.java
- tomcat9/src/test/java/com/hazelcast/session/Tomcat9NonSerializableSessionTest.java
- tomcat9/src/test/java/com/hazelcast/session/Tomcat9SecurityTest.java
- tomcat9/src/test/java/com/hazelcast/session/Tomcat9SessionExpireTest.java
- tomcat9/src/test/java/com/hazelcast/session/nonsticky/Tomcat9ClientServerNonStickySessionsTest.java
- tomcat9/src/test/java/com/hazelcast/session/nonsticky/Tomcat9P2PNonStickySessionsTest.java
- tomcat9/src/test/java/com/hazelcast/session/sticky/Tomcat9ClientServerStickySessionsTest.java
- tomcat9/src/test/java/com/hazelcast/session/sticky/Tomcat9P2PStickySessionsTest.java
This implementation creates a new module for [Apache Tomcat 9](https://tomcat.apache.org/tomcat-9.0-doc/index.html) support.
> Provided support for Tomcat 9

- README.md
- tomcat-core/src/main/java/com/hazelcast/session/HazelcastSession.java
- tomcat-core/src/test/java/com/hazelcast/session/AbstractHazelcastSessionsTest.java
- tomcat-core/src/test/java/com/hazelcast/session/AbstractSessionExpireTest.java
- tomcat-core/src/test/java/com/hazelcast/session/nonsticky/AbstractNonStickySessionsTest.java
- tomcat-core/src/test/resources/hazelcast-1.xml
- tomcat-core/src/test/resources/hazelcast-2.xml
- tomcat-core/src/test/resources/hazelcast-3.xml
- tomcat-core/src/test/resources/hazelcast-4.xml
- tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat7/src/test/java/com/hazelcast/session/Tomcat7AsyncConfigurator.java
- tomcat7/src/test/java/com/hazelcast/session/Tomcat7Configurator.java
- tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat8/src/test/java/com/hazelcast/session/Tomcat8AsyncConfigurator.java
- tomcat8/src/test/java/com/hazelcast/session/Tomcat8Configurator.java
- tomcat85/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat85/src/test/java/com/hazelcast/session/Tomcat85AsyncConfigurator.java
- tomcat85/src/test/java/com/hazelcast/session/Tomcat85Configurator.java
- tomcat9/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat9/src/test/java/com/hazelcast/session/Tomcat9AsyncConfigurator.java
- tomcat9/src/test/java/com/hazelcast/session/Tomcat9Configurator.java
Before this change, Tomcat's background process for expiration was retrieving all the remote sessions to local to check & expire them. This can cause OOMEs when the total session size is larger than the local container's heap. 
To prevent that, the expiration of the sessions in the Hazelcast cluster is separated from Tomcat. Now, Hazelcast's `max-idle-seconds` property is set to `sessionTimeout` value by default to define expiry policy on the cluster side. The configuration is done by adding a dynamic map config to the Hazelcast cluster if there is no configuration for this map in the cluster. If so, then the existing cluster configuration has the priority.
Fixes #83.
> Separated Hazelcast's own session expiration from Tomcat

- pom.xml
```
👉 curl  http://repo2.maven.org/maven2/org/apache/tomcat/tomcat-servlet-api/8.0.36/tomcat-servlet-api-8.0.36.pom -v
*   Trying 92.242.140.2...
* TCP_NODELAY set
* Connected to repo2.maven.org (92.242.140.2) port 80 (#0)
> GET /maven2/org/apache/tomcat/tomcat-servlet-api/8.0.36/tomcat-servlet-api-8.0.36.pom HTTP/1.1
> Host: repo2.maven.org
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 14 Apr 2020 23:23:20 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: close
< Expires: Tue, 14 Apr 2020 23:33:20 GMT
< Cache-Control: max-age=600
< X-Frame-Options: DENY
<
* Closing connection 0
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head> …
```
> fix(pom.xml): Remove deprecated maven dependency

- tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat85/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat9/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
> Fixed concurrency issue when finding sessions

- tomcat-core/src/main/java/com/hazelcast/session/HazelcastSessionChangeValve.java
- tomcat-core/src/test/java/com/hazelcast/session/TestServlet.java
- tomcat-core/src/test/java/com/hazelcast/session/sticky/AbstractStickySessionsTest.java
> Fixed stale local session issue after failover

- pom.xml
- tomcat-core/src/main/java/com/hazelcast/session/ClientServerConfigLoader.java
- tomcat-core/src/main/java/com/hazelcast/session/ClientServerLifecycleListener.java
- tomcat-core/src/main/java/com/hazelcast/session/P2PConfigLoader.java
- tomcat-core/src/main/java/com/hazelcast/session/P2PLifecycleListener.java
- tomcat-core/src/test/java/com/hazelcast/session/ConfigLoaderTest.java
- tomcat-core/src/test/resources/hazelcast-invalid.xml
- tomcat-core/src/test/resources/hazelcast-invalid.yaml
- tomcat-core/src/test/resources/test-hazelcast-client.yaml
- tomcat-core/src/test/resources/test-hazelcast.yaml
> Added YAML configuration support and bumped Hazelcast to v4.0.2

- README.md
- tomcat9/src/main/java/com/hazelcast/session/HazelcastSessionManagerConfiguration.java
Some users might require to disable autoconfiguration if they configure Session Manager manually. This PR adds a new property to allow so.
> Added property to enable/disable Spring Boot autoconfiguration

- tomcat-core/src/main/java/com/hazelcast/session/HazelcastSessionChangeValve.java
- tomcat-core/src/test/java/com/hazelcast/session/sticky/AbstractStickySessionsTest.java
- tomcat6/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat85/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
- tomcat9/src/main/java/com/hazelcast/session/HazelcastSessionManager.java
When sticky sessions are enabled and failover happens, `HazelcastSessionChangeValve` was creating new sessions instead of using the existing one because of a concurrency issue. This was causing users to lose access to the current session.
This PR fixes the mentioned issue.
> Fixes new session creation on failover
